site_name: Ohjurot
site_description: 'Welcome to my GitHub'
site_author: 'Ludwig Fuechsl'
repo_name: 'Ohjurot/Ohjurot'
repo_url: 'https://github.com/ohjurot/ohjurot'
nav:
    - Home: index.md
theme:
  name: 'material'
