site_name: Ohjurot
site_description: 'A docs test'
site_author: 'Ludwig Fuechsl'
repo_name: 'mhausenblas/mkdocs-template'
repo_url: 'https://github.com/ohjurot/ohjurot'
nav:
    - Home: README.md
theme:
  name: 'material'
